---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zot
  namespace: flux-system
spec:
  chart:
    spec:
      chart: zot
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: zot
        namespace: flux-system
      version: 0.1.42
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: zot
  targetNamespace: zot
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      className: nginx
      enabled: true
      hosts:
      - host: fast-and-secure.k8c.io
        paths:
        - path: /
      pathtype: ImplementationSpecific
      tls:
      - hosts:
        - fast-and-secure.k8c.io
        secretName: fast-and-secure
