---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: webserver
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: webserver
  interval: 5m0s
  releaseName: webserver
  targetNamespace: default
