---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: webserver
  namespace: flux-system
spec:
  chart:
    spec:
      verify:
        provider: cosign
      chart: webserver
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: demo-charts
  interval: 5m0s
  releaseName: webserver
  targetNamespace: default
