apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- flux-source-helm-cert-manager-chart.yaml
- flux-source-helm-ingress-nginx-chart.yaml
